---
name: 'Check MyAMI Performance'

on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
        os: ['ubuntu-latest', windows-latest, macos-latest]
    name: ${{ matrix.os }}, Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: "Set Up Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install Dependencies"
        run: |
          python3 -m pip install -r requirements.txt
      - name: 'Run Tests'
        run: |
          python3 -m unittest
